export const DateTimeFormats = {
    LONG_MONTH_FIRST: 'MMMM DD YYYY',
    LONG_DAY_FIRST: 'DD MMMM YYYY',
    SHORT_MONTH_FIRST: 'MM DD YYYY',
    SHORT_DAY_FIRST: 'DD-MM-YYYY',
    LONG_YEAR_FIRST: 'YYYY MMMM DD',
    SHORT_YEAR_FIRST: 'YYYY MM DD',
    TIME_24_HOURS: 'HH:mm',
    TIME_12_HOURS: 'hh:mmA',
    SHORT_DAY_FIRST_12_HOURS: 'DD-MM-YYYY hh:mma'
};
